language: java
install: true
jdk:
- oraclejdk8


jobs:
  include:
    - stage: Unit tests
      script: "./gradlew --daemon --stacktrace test"
    - stage: Deploy to Bintray
      if: branch = master
      script: "./gradlew --stacktrace jar"
      script: "./gradlew --daemon --no-configure-on-demand --no-parallel --stacktrace -PbintrayUser=oslonokkelen -PbintrayKey=$BINTRAY_KEY
  bintrayUpload"

before_cache:
- rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
env:
  global:
    secure: paDOmP1io3W76ObcLptyIzJOwY9t7AshO2t9ZTwfEaTWjvbE9NctDKgwHSEKrYj0sjNEkBLYOqtSK2jR8ZidWZ5hZMfAaioD16j/UyP4AKNeIo8eurxek4U4Nr/WkTl1e3ogt3IQ3GR2PLPkfibm+5NGOZfHgUeJhH5KAZcVJDy4ayac8uR45ydOPTk/pRWgXNgg/I4oCZd/5c2Yk3NSlpAkir2wkiGZ4/nL1EeLmIhSqdO59tAmadaN3+Jv5Y8MEeauHwAbtgoFjn9GwJNMQaMe/6aN2gu/XIMDJMToFprBJ1xBltwKZB/xUN2zxdvC6aK6oReuUEl8vSQcAeD5VBav82ydTDOD41AO8uclRROO7rt9lkjJUowB5NMGqq5l0ni2AhcMg9GmU5Vx8jzZpWanbOJgc+4c7Ywydc/4HjvsLdeNFXW3b8TwKkLX5ZSdwjEaPinlYyFl3tMNX5QMtcQLWH6fq/wYVxNcnxr2IxWIefHR9cEOnhinivjrqCztOEFXqatJ8ob9/NzlLLIQNqRLANTbe0VtTmYdej3NfYOkEYu9tJ8NU2EsTuRx44JpZ7TLNVMZHEX7Fui4LlWjYVMuXW8/J7qFkSj92ABxwhHVesQ3rPIXMhCv+qTtsyrjMIYjdfyUBlNU0SexhdhdjeosRsN2aVJps9ZdPV2VKSk=
